/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.gerhards.liferay.services.angular.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import eu.gerhards.liferay.services.angular.model.AngularTeam;
import eu.gerhards.liferay.services.angular.model.AngularTeamModel;
import eu.gerhards.liferay.services.angular.model.AngularTeamSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AngularTeam service. Represents a row in the &quot;AngularServices_AngularTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AngularTeamModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AngularTeamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AngularTeamImpl
 * @see AngularTeam
 * @see AngularTeamModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AngularTeamModelImpl extends BaseModelImpl<AngularTeam>
	implements AngularTeamModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Team model instance should use the {@link AngularTeam} interface instead.
	 */
	public static final String TABLE_NAME = "AngularServices_AngularTeam";
	public static final Object[][] TABLE_COLUMNS = {
			{ "angularTeamId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("angularTeamId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AngularServices_AngularTeam (angularTeamId LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table AngularServices_AngularTeam";
	public static final String ORDER_BY_JPQL = " ORDER BY angularTeam.angularTeamId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AngularServices_AngularTeam.angularTeamId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.eu.gerhards.liferay.services.angular.model.AngularTeam"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.eu.gerhards.liferay.services.angular.model.AngularTeam"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AngularTeam toModel(AngularTeamSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AngularTeam model = new AngularTeamImpl();

		model.setAngularTeamId(soapModel.getAngularTeamId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AngularTeam> toModels(AngularTeamSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AngularTeam> models = new ArrayList<AngularTeam>(soapModels.length);

		for (AngularTeamSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"lock.expiration.time.eu.gerhards.liferay.services.angular.model.AngularTeam"));

	public AngularTeamModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _angularTeamId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAngularTeamId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _angularTeamId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AngularTeam.class;
	}

	@Override
	public String getModelClassName() {
		return AngularTeam.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("angularTeamId", getAngularTeamId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long angularTeamId = (Long)attributes.get("angularTeamId");

		if (angularTeamId != null) {
			setAngularTeamId(angularTeamId);
		}
	}

	@JSON
	@Override
	public long getAngularTeamId() {
		return _angularTeamId;
	}

	@Override
	public void setAngularTeamId(long angularTeamId) {
		_angularTeamId = angularTeamId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AngularTeam.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AngularTeam toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AngularTeam)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AngularTeamImpl angularTeamImpl = new AngularTeamImpl();

		angularTeamImpl.setAngularTeamId(getAngularTeamId());

		angularTeamImpl.resetOriginalValues();

		return angularTeamImpl;
	}

	@Override
	public int compareTo(AngularTeam angularTeam) {
		int value = 0;

		if (getAngularTeamId() < angularTeam.getAngularTeamId()) {
			value = -1;
		}
		else if (getAngularTeamId() > angularTeam.getAngularTeamId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AngularTeam)) {
			return false;
		}

		AngularTeam angularTeam = (AngularTeam)obj;

		long primaryKey = angularTeam.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AngularTeam> toCacheModel() {
		AngularTeamCacheModel angularTeamCacheModel = new AngularTeamCacheModel();

		angularTeamCacheModel.angularTeamId = getAngularTeamId();

		return angularTeamCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{angularTeamId=");
		sb.append(getAngularTeamId());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append("eu.gerhards.liferay.services.angular.model.AngularTeam");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>angularTeamId</column-name><column-value><![CDATA[");
		sb.append(getAngularTeamId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AngularTeam.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AngularTeam.class
		};
	private long _angularTeamId;
	private AngularTeam _escapedModel;
}