/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.gerhards.liferay.services.angular.model.impl;

import aQute.bnd.annotation.ProviderType;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import eu.gerhards.liferay.services.angular.model.AngularVirtualInstance;
import eu.gerhards.liferay.services.angular.model.AngularVirtualInstanceModel;
import eu.gerhards.liferay.services.angular.model.AngularVirtualInstanceSoap;

import java.io.Serializable;
import java.sql.Types;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the AngularVirtualInstance service. Represents a row in the &quot;AngularServices_AngularVirtualInstance&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AngularVirtualInstanceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AngularVirtualInstanceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AngularVirtualInstanceImpl
 * @see AngularVirtualInstance
 * @see AngularVirtualInstanceModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class AngularVirtualInstanceModelImpl extends BaseModelImpl<AngularVirtualInstance>
	implements AngularVirtualInstanceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Virtual instance model instance should use the {@link AngularVirtualInstance} interface instead.
	 */
	public static final String TABLE_NAME = "AngularServices_AngularVirtualInstance";
	public static final Object[][] TABLE_COLUMNS = {
			{ "virtualInstanceId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("virtualInstanceId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AngularServices_AngularVirtualInstance (virtualInstanceId LONG not null primary key)";
	public static final String TABLE_SQL_DROP = "drop table AngularServices_AngularVirtualInstance";
	public static final String ORDER_BY_JPQL = " ORDER BY angularVirtualInstance.virtualInstanceId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AngularServices_AngularVirtualInstance.virtualInstanceId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.eu.gerhards.liferay.services.angular.model.AngularVirtualInstance"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.eu.gerhards.liferay.services.angular.model.AngularVirtualInstance"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static AngularVirtualInstance toModel(
		AngularVirtualInstanceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		AngularVirtualInstance model = new AngularVirtualInstanceImpl();

		model.setVirtualInstanceId(soapModel.getVirtualInstanceId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<AngularVirtualInstance> toModels(
		AngularVirtualInstanceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<AngularVirtualInstance> models = new ArrayList<AngularVirtualInstance>(soapModels.length);

		for (AngularVirtualInstanceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(eu.gerhards.liferay.services.angular.service.util.ServiceProps.get(
				"lock.expiration.time.eu.gerhards.liferay.services.angular.model.AngularVirtualInstance"));

	public AngularVirtualInstanceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _virtualInstanceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setVirtualInstanceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _virtualInstanceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AngularVirtualInstance.class;
	}

	@Override
	public String getModelClassName() {
		return AngularVirtualInstance.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("virtualInstanceId", getVirtualInstanceId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long virtualInstanceId = (Long)attributes.get("virtualInstanceId");

		if (virtualInstanceId != null) {
			setVirtualInstanceId(virtualInstanceId);
		}
	}

	@JSON
	@Override
	public long getVirtualInstanceId() {
		return _virtualInstanceId;
	}

	@Override
	public void setVirtualInstanceId(long virtualInstanceId) {
		_virtualInstanceId = virtualInstanceId;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			AngularVirtualInstance.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AngularVirtualInstance toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AngularVirtualInstance)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AngularVirtualInstanceImpl angularVirtualInstanceImpl = new AngularVirtualInstanceImpl();

		angularVirtualInstanceImpl.setVirtualInstanceId(getVirtualInstanceId());

		angularVirtualInstanceImpl.resetOriginalValues();

		return angularVirtualInstanceImpl;
	}

	@Override
	public int compareTo(AngularVirtualInstance angularVirtualInstance) {
		int value = 0;

		if (getVirtualInstanceId() < angularVirtualInstance.getVirtualInstanceId()) {
			value = -1;
		}
		else if (getVirtualInstanceId() > angularVirtualInstance.getVirtualInstanceId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AngularVirtualInstance)) {
			return false;
		}

		AngularVirtualInstance angularVirtualInstance = (AngularVirtualInstance)obj;

		long primaryKey = angularVirtualInstance.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<AngularVirtualInstance> toCacheModel() {
		AngularVirtualInstanceCacheModel angularVirtualInstanceCacheModel = new AngularVirtualInstanceCacheModel();

		angularVirtualInstanceCacheModel.virtualInstanceId = getVirtualInstanceId();

		return angularVirtualInstanceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(3);

		sb.append("{virtualInstanceId=");
		sb.append(getVirtualInstanceId());

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(7);

		sb.append("<model><model-name>");
		sb.append(
			"eu.gerhards.liferay.services.angular.model.AngularVirtualInstance");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>virtualInstanceId</column-name><column-value><![CDATA[");
		sb.append(getVirtualInstanceId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AngularVirtualInstance.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AngularVirtualInstance.class
		};
	private long _virtualInstanceId;
	private AngularVirtualInstance _escapedModel;
}