/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.gerhards.liferay.services.angular.model.impl;

import aQute.bnd.annotation.ProviderType;

import eu.gerhards.liferay.services.angular.model.AngularTeam;
import eu.gerhards.liferay.services.angular.service.AngularTeamLocalServiceUtil;

/**
 * The extended model base implementation for the AngularTeam service. Represents a row in the &quot;AngularServices_AngularTeam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AngularTeamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AngularTeamImpl
 * @see AngularTeam
 * @generated
 */
@ProviderType
public abstract class AngularTeamBaseImpl extends AngularTeamModelImpl
	implements AngularTeam {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a Team model instance should use the {@link AngularTeam} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AngularTeamLocalServiceUtil.addAngularTeam(this);
		}
		else {
			AngularTeamLocalServiceUtil.updateAngularTeam(this);
		}
	}
}