/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.gerhards.liferay.services.angular.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AngularPortal service. Represents a row in the &quot;AngularServices_AngularPortal&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.gerhards.liferay.services.angular.model.impl.AngularPortalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.gerhards.liferay.services.angular.model.impl.AngularPortalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AngularPortal
 * @see eu.gerhards.liferay.services.angular.model.impl.AngularPortalImpl
 * @see eu.gerhards.liferay.services.angular.model.impl.AngularPortalModelImpl
 * @generated
 */
@ProviderType
public interface AngularPortalModel extends BaseModel<AngularPortal> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Portal model instance should use the {@link AngularPortal} interface instead.
	 */

	/**
	 * Returns the primary key of this Portal.
	 *
	 * @return the primary key of this Portal
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Portal.
	 *
	 * @param primaryKey the primary key of this Portal
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the portal ID of this Portal.
	 *
	 * @return the portal ID of this Portal
	 */
	public long getPortalId();

	/**
	 * Sets the portal ID of this Portal.
	 *
	 * @param portalId the portal ID of this Portal
	 */
	public void setPortalId(long portalId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.gerhards.liferay.services.angular.model.AngularPortal angularPortal);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.gerhards.liferay.services.angular.model.AngularPortal> toCacheModel();

	@Override
	public eu.gerhards.liferay.services.angular.model.AngularPortal toEscapedModel();

	@Override
	public eu.gerhards.liferay.services.angular.model.AngularPortal toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}