/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package eu.gerhards.liferay.services.angular.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AngularVirtualHost service. Represents a row in the &quot;AngularServices_AngularVirtualHost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link eu.gerhards.liferay.services.angular.model.impl.AngularVirtualHostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link eu.gerhards.liferay.services.angular.model.impl.AngularVirtualHostImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AngularVirtualHost
 * @see eu.gerhards.liferay.services.angular.model.impl.AngularVirtualHostImpl
 * @see eu.gerhards.liferay.services.angular.model.impl.AngularVirtualHostModelImpl
 * @generated
 */
@ProviderType
public interface AngularVirtualHostModel extends BaseModel<AngularVirtualHost> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a Virtual host model instance should use the {@link AngularVirtualHost} interface instead.
	 */

	/**
	 * Returns the primary key of this Virtual host.
	 *
	 * @return the primary key of this Virtual host
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this Virtual host.
	 *
	 * @param primaryKey the primary key of this Virtual host
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the virtual host ID of this Virtual host.
	 *
	 * @return the virtual host ID of this Virtual host
	 */
	public long getVirtualHostId();

	/**
	 * Sets the virtual host ID of this Virtual host.
	 *
	 * @param virtualHostId the virtual host ID of this Virtual host
	 */
	public void setVirtualHostId(long virtualHostId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		eu.gerhards.liferay.services.angular.model.AngularVirtualHost angularVirtualHost);

	@Override
	public int hashCode();

	@Override
	public CacheModel<eu.gerhards.liferay.services.angular.model.AngularVirtualHost> toCacheModel();

	@Override
	public eu.gerhards.liferay.services.angular.model.AngularVirtualHost toEscapedModel();

	@Override
	public eu.gerhards.liferay.services.angular.model.AngularVirtualHost toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}